### ISSUE TITLE
prednote-test doesn't support latest prednote 

### ISSUE THREAD

**Issue by peti** [massysett/prednote#1]
Will you update prednote-test, too?

http://packdeps.haskellers.com/feed?needle=prednote-test

**Comment by massysett** [comment]
Short answer: no; I will deprecate prednote-test.

Long answer: No; figuring out how best to handle QuickCheck tests has been a struggle.  For now I have decided to use orphan instances for Arbitrary and CoArbitrary, which makes writing the tests MUCH simpler.  However I would rather not release any library with orphan instances, even if they are just for tests.  So I didn't put the orphans in prednote-test; rather, I put them as an executable in the main prednote package.  The original reason I made prednote-test was to allow other packages to use the tests and (more importantly) their generators, but for now a simple copy-paste will have to work for those purposes.

I'm finding there is no perfect way to handle the tests.  Advantages of putting them in the main package and not as a library: makes orphans more OK, which makes the tests MUCH easier to write; everything is in one package, which is less work to maintain.  Disadvantages: other packages can't use the generators and so they must resort to primitive copy-paste.  But since no way is perfect, I will try this method to see if it is the least bad.

**Comment by peti** [comment]
I've made similar experiences. The `Arbitrary` type looks good on first glance, but more usually the is no one single way to define that instance so that its results are useful for all kinds of tests. I ended up using explicit generators almost all the time, i.e. I don't bother with the `arbitrary` generator, and I don't define such an instance for my own types. This has the added advantage that it allows me to keep the QuickCheck dependency out of the main code. Anyway, I guess there's no silver bullet here.

**Comment by massysett** [comment]
I did write a library, barecheck, to help out with using QuickCheck without Arbitrary.

https://github.com/massysett/barecheck

For instance it's hard to generate random functions without using Arbitrary; barecheck gives you a non-overloaded generator you can use for this.
